name: Policy as Code

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  policy-as-code:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.GIT_APP_ID }}
          private-key: ${{ secrets.GIT_APP_PRIVATE_KEY }}

      - name: Security Compliance Action
        uses: advanced-security/policy-as-code@main
        with:
          # Which repository the policy is stored
          policy: advanced-security/security
          # The local (within the workspace) or repository
          policy-path: policies/production.yml
          # [optional] The branch you want to target
          policy-branch: main
          # GitHub Personal Access Token to access the GitHub API.
          # Secret Scanning and Dependabot do not allow their resources to be
          #  exposed to Actions so this might need to be set using a token that has
          #  the ability to access the resources
          token: ${{ steps.app-token.outputs.token }}
          # [optional]: What action to take if the policy requirements are broken
          action: continue
          # This is needed to 
          argvs: "--is-github-app-token"
