#!/bin/bash

SCRIPT_PATH=$(realpath ${BASH_SOURCE[0]})
SCRIPT_DIR=$(dirname $SCRIPT_PATH)

# Check if python3 is installed
if command -v python3 &> /dev/null; then
    # We need to add the vendor directory to the PYTHONPATH
    export PYTHONPATH=$SCRIPT_DIR/vendor:$SCRIPT_DIR
    python3 -m ghascompliance $@
else 
    echo "Python is not installed. Please install Python (+3.9) and try again."
    echo "Make sure that Python is added to the PATH environment variable."
    exit 1
fi

