"""CodeScanningChecker."""
from typing import List, Optional

from ghastoolkit import CodeAlert, CodeScanning, GitHub

from ghascompliance.policies.base import CodeScanningPolicy
from ghascompliance.checks.checker import Checker
from ghascompliance.octokit.octokit import Octokit
from ghascompliance.policies.severities import SeverityLevelEnum


class CodeScanningChecker(Checker):
    """Code Scanning checker."""

    def enabled(self) -> bool:
        """Check to see if code scanning is enabled in the policy."""
        if isinstance(self.policy.codescanning, (list)):
            return True  # assume that as list is enabled
        else:
            return self.policy.codescanning.enabled

    def error(self, alert: CodeAlert, check_name: Optional[str] = None):
        """Log a Code Scanning error."""
        err = f"{alert.tool_name} - {alert.created_at} - {alert.rule_id}"
        if Octokit.debugging_enabled():
            err += f" ({check_name})"
        self.state.error(err)

    def warning(self, alert: CodeAlert):
        """Warning."""
        self.state.warning(f"{alert.tool_name} - {alert.created_at} - {alert.rule_id}")

    def check(self):
        """Check Code Scanning alerts."""
        codescanning = CodeScanning()
        # check: is enabled

        alerts = self.getAlerts()
        Octokit.info("Total Code Scanning Alerts :: " + str(len(alerts)))

        policies: List[CodeScanningPolicy] = []
        Octokit.debug(f"Total Code Scanning Policies :: {len(policies)}")

        if isinstance(self.policy.codescanning, CodeScanningPolicy):
            policies.append(self.policy.codescanning)
        else:
            policies.extend(self.policy.codescanning)

        for policy in policies:
            if policy.enabled and codescanning.isEnabled():
                self.state.critical(f"Code Scanning is not enabled")
                return

            # severities
            self.severities = SeverityLevelEnum.getSeveritiesFromName(
                policy.severity.value
            )

            # tool required check
            if policy.tools_required:
                self.checkTools(policy.tools_required)

            for alert in alerts:
                self.checkCodeScanningAlert(policy, alert)

    def getAlerts(self) -> List[CodeAlert]:
        """Get Alerts from Code Scanning."""
        codescanning = CodeScanning()

        if GitHub.repository.isInPullRequest():
            Octokit.info("Code Scanning Alerts from Pull Request (alert diff)")
            pr_base = (
                GitHub.repository.getPullRequestInfo().get("base", {}).get("ref", "")
            )
            alerts: List[CodeAlert] = codescanning.getAlertsInPR(pr_base)

        else:
            Octokit.debug(
                f"Code Scanning Alerts from reference :: {GitHub.repository.reference}"
            )
            alerts: List[CodeAlert] = codescanning.getAlerts(
                "open", ref=GitHub.repository.reference
            )
        return alerts

    def checkCodeScanningAlert(self, policy: CodeScanningPolicy, alert: CodeAlert):
        """Check Code Scanning Alert to see if it violates the provided policy."""
        # tools
        if len(policy.tools) != 0:
            if alert.tool_name not in policy.tools:
                Octokit.debug(f"Alert wasn't generated by the required tool")
                return

        # severity
        if alert.severity in self.severities:
            self.error(alert, "severity")
            return

        # ignore ids
        alert_id = alert.rule_id
        if self.matchContent(alert_id, policy.ids_ignores):
            return
        # warning ids
        if self.matchContent(alert_id, policy.ids_warnings):
            self.warning(alert)
            return
        # ids to error on
        if self.matchContent(alert_id, policy.ids):
            self.error(alert, "id match")
            return

        # names / description
        if self.matchContent(alert.description, policy.names):
            self.error(alert)
            return

        # TODO cwes

        # TODO owasp

        return

    def checkTools(self, tools: List[str]):
        cstools = CodeScanning().getTools()
        for tool in tools:
            if tool in cstools:
                continue

            self.state.error(f"Required tool missing :: {tool}")

        return
